const searchResults = [
     'Laptop',
     'Mobile',
     'Tablets',
     'Acer',
     'Vivo',
     'Lenevo',
     'Macbook',
     'Acer Nitro',
     'Macbook Air',
     'Laptop Bags',
     'Laptop Bags under 1000',
     'Iphone',
     'Iphone 14',
     'Samsung',
     'Android',
     'Rasberry pi',
     'Smart watch',
     'Asus',
     'Asus ROG',
     'Iphone 8',
     'Iphone 7',
     'Iphone case',
     'Samsung Galaxy Note',
     'Poco Phone',
     'Redmi',
     'Redmi Note',
     'Airpod',
     'Earphone',
     'Headphone',
     'Samsung S7 Edge',
     'Samsung Phone Under 20000',
     'Readmi Earphone',
     'Notebook',
     'SSD',
     'HDD',
     'Solid State Drive',
     'Hard Disk Drive',
     'RAM',
     'Monitor',
     'Ultrabook',
     'Beats',
     'Beats Headphone',
     'Keyboard',
     'Mouse',
     'Wireless Keyboard',
     'Wireless Mouse',
     'Wireless Earphone',
     'Wireless Headphone'
]

export default searchResults